version: "3"

services:

  ### nexus ################################################
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme
    command: daemon
    volumes:
      - ./acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=${DOMAIN_NAME}
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/${DOMAIN_NAME}/key.key
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/${DOMAIN_NAME}/cert.crt"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/${DOMAIN_NAME}/ca.crt"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/${DOMAIN_NAME}/fullchain.crt"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"
      - DEPLOY_SSH_USER=ubuntu
      - DEPLOY_SSH_CMD=ssh
      - DEPLOY_SSH_SERVER=${DEPLOY_SSH_SERVER}
      - DEPLOY_SSH_KEYFILE=${DEPLOY_SSH_KEYFILE}
      - DEPLOY_SSH_CERTFILE=${DEPLOY_SSH_CERTFILE}
      - DEPLOY_SSH_CAFILE=${DEPLOY_SSH_CAFILE}
      - DEPLOY_SSH_FULLCHAIN=${DEPLOY_SSH_FULLCHAIN}
      # - DEPLOY_SSH_REMOTE_CMD=command to execute on remote host
      # - DEPLOY_SSH_BACKUP=yes or no

  ### nexus ################################################
  nexus:
    image: sonatype/nexus3
    # restart: always
    hostname: ${DOMAIN_NAME_NEXUS}
    container_name: nexus
    ports:
      - "${NEXUS_HTTP_PORT}:8081"
    volumes:
      - ./nexus-data:/nexus-data

  ### Gitlab ################################################
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "${DOMAIN_NAME_GIT}"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${DOMAIN_NAME_GIT}"
        nginx['listen_https'] = true
        nginx['redirect_http_to_https'] = true
        sidekiq['concurrency'] = 64
        letsencrypt['enable'] = "${GITLAB_LETSENCRYPT}"
        letsencrypt['auto_renew'] = "${GITLAB_LETSENCRYPT_RENEW}"
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        # nginx['ssl_certificate'] = "/etc/gitlab/${DOMAIN_NAME_GIT}.crt"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/${DOMAIN_NAME_GIT}.key"
        # nginx['custom_nginx_config'] = "include /etc/gitlab/nexus.conf;"
        # nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
        # gitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']
        # gitlab_rails['gitlab_shell_ssh_port'] = 22
        # redis['enable'] = false
        # gitlab_rails['redis_host'] = 'redis'
        # gitlab_rails['redis_database'] = 8
        # postgresql['enable'] = false
        # gitlab_rails['db_host'] = 'postgres'
        # gitlab_rails['db_username'] = 'laradock_gitlab'
        # gitlab_rails['db_password'] = 'laradock_gitlab'
        # gitlab_rails['db_database'] = 'laradock_gitlab'
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
      - "./gitlab/log:/var/log/gitlab"
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"

  ### awvs ################################################
  awvs:
    image: secfa/docker-awvs
    ports:
      - "3443:3443"
    # networks:
    #   - backend
    # restart: always

  ### Nessus ################################################
  nessus:
    image: tenableofficial/nessus
    container_name: nessus
    ports:
      - "8834:8834"
    environment:
      - ACTIVATION_CODE=${NESSUS_ACTIVE_CODE}
      - USERNAME=${NESSUS_USER}
      - PASSWORD=${NESSUS_PASS}
      - SECURITYCENTER=yes
    # networks:
    #   - backend
    # restart: always

  ### watchtower ################################################
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #- /home/ubuntu/.docker/config.json:/config.json
    #command: --interval 300
